import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Component/Header";
import Footer from "./Component/Footer";
import { ClerkProvider } from "@clerk/nextjs";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rental E-Commerce",
  description: "Generated by create next app",
};


export default function RootLayout ( {
  children,
}:{
  children : React.ReactNode
}) {
  return (
    <ClerkProvider> 
      <html lang="en">
      <head>
        {/* Add favicon link */}
        <link rel="icon" href="/titleimg.jpg" />
      </head>
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>

   
  )
}